<?php
/**
 * Plugin Name:       SpamLens
 * Plugin URI:        https://github.com/veronalabs/spamlens
 * Description:       Spam protection for comments, reviews and Contact Form 7 powered by Jev, TypeSafe AI's decision model.
 * Version:           1.0.0
 * Requires at least: 6.4
 * Tested up to:      7.1
 * Requires PHP:      7.4
 * Author:            VeronaLabs
 * Author URI:        https://veronalabs.com/
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       spamlens
 * Domain Path:       /resources/languages
 *
 * @package SpamLens
 */

defined( 'ABSPATH' ) || exit;

/*
 * Autoloader. A release ships packages/autoload.php (generated by WP Scoper on `composer install`); a development
 * checkout can also use Composer's own vendor/autoload.php.
 */
if ( file_exists( __DIR__ . '/packages/autoload.php' ) ) {
	require_once __DIR__ . '/packages/autoload.php';
} elseif ( file_exists( __DIR__ . '/vendor/autoload.php' ) ) {
	require_once __DIR__ . '/vendor/autoload.php';
} else {
	add_action(
		'admin_notices',
		static function () {
			if ( current_user_can( 'activate_plugins' ) ) {
				echo '<div class="notice notice-error"><p>' . esc_html__( 'SpamLens is missing its autoloader. Run composer install in the plugin folder, or install the release zip.', 'spamlens' ) . '</p></div>';
			}
		}
	);
	return;
}

require_once __DIR__ . '/src/constants.php';

SpamLens\Bootstrap::init();
